# config/IIMGF/train.yaml
data:
  derm7pt_path: '/home/wyl/work/data/derm7pt/release_v0'

model:
  gpu_idx: '1'
  model_path: ''
  pretrained_path: '/home/wyl/work/mamba_code/mamba_test/vssm1_tiny_0230s_ckpt_epoch_264.pth'

output:
  log_path: ./results
  model_path: '/home/wyl/work/Rebuttal/IIMGF_yaml/results/train_1/bestacc_model_75.pth'
